/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class sila_cryptography_LibSilKZG */

#ifndef _Included_sila_cryptography_LibSilKZG
#define _Included_sila_cryptography_LibSilKZG
#ifdef __cplusplus
extern "C" {
#endif
#undef sila_cryptography_LibSilKZG_BYTES_PER_COMMITMENT
#define sila_cryptography_LibSilKZG_BYTES_PER_COMMITMENT 48L
#undef sila_cryptography_LibSilKZG_BYTES_PER_PROOF
#define sila_cryptography_LibSilKZG_BYTES_PER_PROOF 48L
#undef sila_cryptography_LibSilKZG_BYTES_PER_FIELD_ELEMENT
#define sila_cryptography_LibSilKZG_BYTES_PER_FIELD_ELEMENT 32L
#undef sila_cryptography_LibSilKZG_BYTES_PER_BLOB
#define sila_cryptography_LibSilKZG_BYTES_PER_BLOB 131072L
#undef sila_cryptography_LibSilKZG_MAX_NUM_COLUMNS
#define sila_cryptography_LibSilKZG_MAX_NUM_COLUMNS 128L
#undef sila_cryptography_LibSilKZG_BYTES_PER_CELL
#define sila_cryptography_LibSilKZG_BYTES_PER_CELL 2048L
/*
 * Class:     sila_cryptography_LibSilKZG
 * Method:    DASContextNew
 * Signature: (Z)J
 */
JNIEXPORT jlong JNICALL Java_sila_cryptography_LibSilKZG_DASContextNew
  (JNIEnv *, jclass, jboolean);

/*
 * Class:     sila_cryptography_LibSilKZG
 * Method:    DASContextDestroy
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_sila_cryptography_LibSilKZG_DASContextDestroy
  (JNIEnv *, jclass, jlong);

/*
 * Class:     sila_cryptography_LibSilKZG
 * Method:    computeCellsAndKZGProofs
 * Signature: (J[B)Lsila/cryptography/CellsAndProofs;
 */
JNIEXPORT jobject JNICALL Java_sila_cryptography_LibSilKZG_computeCellsAndKZGProofs
  (JNIEnv *, jclass, jlong, jbyteArray);

/*
 * Class:     sila_cryptography_LibSilKZG
 * Method:    computeCells
 * Signature: (J[B)Lsila/cryptography/Cells;
 */
JNIEXPORT jobject JNICALL Java_sila_cryptography_LibSilKZG_computeCells
  (JNIEnv *, jclass, jlong, jbyteArray);

/*
 * Class:     sila_cryptography_LibSilKZG
 * Method:    blobToKZGCommitment
 * Signature: (J[B)[B
 */
JNIEXPORT jbyteArray JNICALL Java_sila_cryptography_LibSilKZG_blobToKZGCommitment
  (JNIEnv *, jclass, jlong, jbyteArray);

/*
 * Class:     sila_cryptography_LibSilKZG
 * Method:    verifyCellKZGProofBatch
 * Signature: (J[[B[J[[B[[B)Z
 */
JNIEXPORT jboolean JNICALL Java_sila_cryptography_LibSilKZG_verifyCellKZGProofBatch
  (JNIEnv *, jclass, jlong, jobjectArray, jlongArray, jobjectArray, jobjectArray);

/*
 * Class:     sila_cryptography_LibSilKZG
 * Method:    recoverCellsAndKZGProofs
 * Signature: (J[J[[B)Lsila/cryptography/CellsAndProofs;
 */
JNIEXPORT jobject JNICALL Java_sila_cryptography_LibSilKZG_recoverCellsAndKZGProofs
  (JNIEnv *, jclass, jlong, jlongArray, jobjectArray);

/*
 * Class:     sila_cryptography_LibSilKZG
 * Method:    computeKzgProof
 * Signature: (J[B[B)[[B
 */
JNIEXPORT jobjectArray JNICALL Java_sila_cryptography_LibSilKZG_computeKzgProof
  (JNIEnv *, jclass, jlong, jbyteArray, jbyteArray);

/*
 * Class:     sila_cryptography_LibSilKZG
 * Method:    computeBlobKzgProof
 * Signature: (J[B[B)[B
 */
JNIEXPORT jbyteArray JNICALL Java_sila_cryptography_LibSilKZG_computeBlobKzgProof
  (JNIEnv *, jclass, jlong, jbyteArray, jbyteArray);

/*
 * Class:     sila_cryptography_LibSilKZG
 * Method:    verifyKzgProof
 * Signature: (J[B[B[B[B)Z
 */
JNIEXPORT jboolean JNICALL Java_sila_cryptography_LibSilKZG_verifyKzgProof
  (JNIEnv *, jclass, jlong, jbyteArray, jbyteArray, jbyteArray, jbyteArray);

/*
 * Class:     sila_cryptography_LibSilKZG
 * Method:    verifyBlobKzgProof
 * Signature: (J[B[B[B)Z
 */
JNIEXPORT jboolean JNICALL Java_sila_cryptography_LibSilKZG_verifyBlobKzgProof
  (JNIEnv *, jclass, jlong, jbyteArray, jbyteArray, jbyteArray);

/*
 * Class:     sila_cryptography_LibSilKZG
 * Method:    verifyBlobKzgProofBatch
 * Signature: (J[[B[[B[[B)Z
 */
JNIEXPORT jboolean JNICALL Java_sila_cryptography_LibSilKZG_verifyBlobKzgProofBatch
  (JNIEnv *, jclass, jlong, jobjectArray, jobjectArray, jobjectArray);

#ifdef __cplusplus
}
#endif
#endif
