name: Node Bindings
env:
  DEBUG: napi:*
  APP_NAME: node-sil-kzg
  MACOSX_DEPLOYMENT_TARGET: '10.13'
  COREPACK_ENABLE_AUTO_PIN: 0
permissions:
  contents: write
  id-token: write

concurrency:
  group: ${{ github.workflow }}-${{ github.event_name == 'workflow_dispatch' && 'manual' || github.ref }}
  cancel-in-progress: true

on:
  push:
    branches: [ "main", "sila/identity-conversion-rust-sil-kzg-v0.8.0" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
    inputs:
      ref:
        description: The reference (branch/tag/commit) to checkout
        required: false
      release-type:
        type: choice
        required: false
        default: none
        description: Indicates whether we want to make a release and if which one
        options:
          - candidate # Publish version 0.8.0 under the candidate dist-tag
          - none # Build and test only

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        settings:
          - host: macos-14
            target: x86_64-apple-darwin
          - host: macos-14
            target: aarch64-apple-darwin
          - host: ubuntu-latest
            target: x86_64-unknown-linux-gnu
          - host: ubuntu-latest
            target: aarch64-unknown-linux-gnu
          - host: ubuntu-latest
            target: x86_64-pc-windows-msvc
          - host: ubuntu-latest
            target: aarch64-pc-windows-msvc

    name: Build - ${{ matrix.settings.target }}
    runs-on: ${{ matrix.settings.host }}
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ inputs.ref || github.ref }}
      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Enable Yarn 4.18.0
        run: corepack enable && corepack prepare yarn@4.18.0 --activate
      - name: Install Rust
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: 1.86.0
          targets: ${{ matrix.settings.target }}

      # llvm-preview-tools are needed for xwin, because we are compiling assembly (blst)
      # Alternatively, you can install llvm
      - name: Install llvm-preview-tools
        if: runner.os == 'Linux' && contains(matrix.settings.target, 'windows')
        run: rustup component add llvm-tools-preview 
      - name: Install dependencies
        run: yarn install --immutable
        working-directory: bindings/node
      - name: Setup Zig
        uses: goto-bus-stop/setup-zig@v2
        with:
          version: 0.13.0
        
      - name: Install Binstall
        uses: cargo-bins/cargo-binstall@main

      - name: Install cargo-zigbuild
        run: cargo binstall cargo-zigbuild@0.20.0 -y

      - name: Install cargo-xwin (Windows on Linux only)
        if: contains(matrix.settings.target, 'windows')
        run: cargo binstall cargo-xwin -y

      - name: Build Linux
        if: contains(matrix.settings.target, 'linux')
        run: yarn build --zig --release --target ${{ matrix.settings.target }}
        working-directory: bindings/node

      - name: Build Mac
        if: contains(matrix.settings.target, 'apple')
        run: yarn build --release --target ${{ matrix.settings.target }}
        working-directory: bindings/node

      - name: Build (Windows on Linux)
        if: contains(matrix.settings.target, 'windows')
        run: yarn build --release --target ${{ matrix.settings.target }}
        working-directory: bindings/node

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: bindings-${{ matrix.settings.target }}
          path: bindings/node/${{ env.APP_NAME }}.*.node
          if-no-files-found: error

  test:
    needs: build
    strategy:
      fail-fast: false
      matrix:
        settings:
          - host: macos-13
            target: x86_64-apple-darwin
          - host: macos-14
            target: aarch64-apple-darwin
          - host: ubuntu-latest
            target: x86_64-unknown-linux-gnu
          - host: ubuntu-latest
            target: aarch64-unknown-linux-gnu
          - host: windows-latest
            target: x86_64-pc-windows-msvc
          - host: ubuntu-latest
            target: aarch64-pc-windows-msvc
        node:
          - '20'

    name: Test - ${{ matrix.settings.target }} - node@${{ matrix.node }}
    runs-on: ${{ matrix.settings.host }}
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ inputs.ref || github.ref }}
      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}
      - name: Enable Yarn 4.18.0
        run: corepack enable && corepack prepare yarn@4.18.0 --activate
      - name: Install dependencies
        run: yarn install --immutable
        working-directory: bindings/node
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: bindings-${{ matrix.settings.target }}
          path: bindings/node
      
      # Native testing for macOS (both Intel and ARM)
      - name: Test bindings (macOS)
        if: startsWith(matrix.settings.host, 'macos')
        run: yarn test
        working-directory: bindings/node

      # Native testing for x86_64 Linux
      - name: Test bindings (Linux x86_64)
        if: matrix.settings.target == 'x86_64-unknown-linux-gnu'
        run: yarn test
        working-directory: bindings/node

      # Emulated testing for aarch64 Linux
      - name: Set up QEMU
        if: matrix.settings.target == 'aarch64-unknown-linux-gnu'
        uses: docker/setup-qemu-action@v3
        with:
          platforms: arm64
      - name: Test bindings (Linux ARM64)
        if: matrix.settings.target == 'aarch64-unknown-linux-gnu'
        uses: addnab/docker-run-action@v3
        with:
          image: node:${{ matrix.node }}-slim
          options: '--platform linux/arm64 -v ${{ github.workspace }}:/build -w /build'
          run: |
            cd bindings/node
            yarn config set supportedArchitectures.cpu "arm64"
            yarn config set supportedArchitectures.libc "glibc"
            yarn install --immutable
            yarn test

      # Native testing for x86_64 Windows
      - name: Test bindings (Windows x86_64)
        if: matrix.settings.target == 'x86_64-pc-windows-msvc'
        run: yarn test
        working-directory: bindings/node
      # ARM on windows is not tested

  publish:
    name: Publish
    runs-on: ubuntu-latest
    needs:
      - test
    defaults:
      run:
        working-directory: bindings/node
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ inputs.ref || github.ref }}
      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: https://registry.npmjs.org
      - name: Enable Yarn 4.18.0
        run: corepack enable && corepack prepare yarn@4.18.0 --activate
      - name: Install dependencies
        run: yarn install --immutable
      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: bindings/node/artifacts
      - name: Move artifacts
        run: yarn artifacts
      - name: Publish
        if: ${{ inputs.release-type == 'candidate' && github.event_name == 'workflow_dispatch' }}
        run: |
          npm config set provenance true
          export NPM_CONFIG_TAG=candidate
          yarn prepareAndPublishAddons
          npm publish --access public --tag candidate
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.NPM_RELEASE_TOKEN }}
